### PR TITLE
add item extent property

### PR DESCRIPTION
**Pull request by htoopyaelinn56**
The UI starts to freeze when the user scroll the list with thousands of items in list. To prevent this, there is [itemExtent](https://api.flutter.dev/flutter/widgets/ListView/itemExtent.html) property in `listview.builder` and you can specify this to set the height of each item in list. I made a little customization to item builder to add the `itemExtent` property and changed the initial items of simple table to 3000. The list view scrolls smoothly if the `itemExtent` is specified but starts to freeze when it is null.

### CODE REVIEW

**Review by MayLau-CbL — APPROVED** [review]
Thanks for the contribution! The PR looks good to me. May I ask which platform you facing the laggy issue?

**Comment by htoopyaelinn56** [comment]
Yes. I face the issue in windows and macOS but it will be likely to happen in mobile devices too.

**Comment by MayLau-CbL** [comment]
i see. I will also update along the doc and some minor issue together in the next version. Let me notify you here later tonight or tmr when it releases. Thanks again for helping contribute!

**Comment by MayLau-CbL** [comment]
Released along in [4.2.0](https://pub.dev/packages/horizontal_data_table) 🙌

**Pull request merged**
