### PR TITLE
Update sync_scroll_controller_manager.dart to make list refresh more smooth

### PR DESCRIPTION
**Pull request by yingshaoxo**
This probably the simplest way to make it work. 

And this makes the refresh more smooth.

### CODE REVIEW

**Comment by yingshaoxo** [comment]
Hello?

**Comment by MayLau-CbL** [comment]
Hey, just notice this PR. I will review this the coming weekend. Thanks!

And btw, just if you have time, do you mind helping to check if this pr is ok to work with WaterDropHeader? As i remember there is some problem when using the offset directly when the state is can_refresh

**Comment by yingshaoxo** [comment]
OK, I'll check it out later in this week

**Comment by yingshaoxo** [comment]
@MayLau-CbL 


It's working without any problem as I tested.

**Comment by MayLau-CbL** [comment]
Sorry to get you back late. The code is all good, i will include this in the next release this weekend. Will let you know tge status here. And thank you very much again for the contribution!

**Comment by MayLau-CbL** [comment]
This PR is available on the v3.4.2 on pub.dev.

**Pull request merged**
