### PR TITLE
Added support to run the example app under Windows, Mac, Linux

### PR DESCRIPTION
**Pull request by guyluz11**
Running the [command](https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app) 
`flutter create --platforms=windows,macos,linux .`
on example folder in order to add support for `Windows`, `Mac`, `Linux`.

### CODE REVIEW

**Comment by guyluz11** [comment]
Solving: #94

**Comment by MayLau-CbL** [comment]
Hi, @guyluz11 ! I have reviewed your pull request, everything works good , thank you! 
Would you mind help remove the following files?
1. analysis_options.yaml
I want to remove this file temporally because I am still working on the lint 2.0 which is not supported for now. 

2. example/README.md
since this is not used in the example project, i want to remove it

3. example/test folder and inner files
same, it is not being used and thus want to remove the folder and the inner file

**Comment by guyluz11** [comment]
> 1. I want to remove this file temporally because I am still working on the lint 2.0 which is not supported for now.

I think commenting on all of `analysis_options.yaml` for now will be a better option, I don't know a lot about lint 2.0 but I think we should change the file for lint 2 instead of removing it.


>     2. example/README.md
>        since this is not used in the example project, I want to remove it

I think it will be good to have it too, but since opening the example folder in GitHub show the content of the file and we can write the specific content about the example and not the library, but I will remove it for now as you asked.


> 3\. example/test folder and inner files
>        same, it is not being used and thus want to remove the folder and the inner file

From my point of view we can add tests and keeping the test folder is good for the structure of the project.
I will remove it now as you asked.

**Review by MayLau-CbL — APPROVED** [review]
Thanks for the update. This PR will release with a later on example update together this weekend. I will let you know on the comment when it is released.

For lint 2.0 is still working on progress. Unless developer fork a version or clone the code directly to their library and upgrade to lint 2.0, others using package import from pubspec should not be affected for now.

**Pull request merged**
